spring.application.name=PAYMENT-SERVICE

spring.datasource.url=jdbc:postgresql://localhost:5433/payments_db
spring.datasource.username=postgres
spring.datasource.password=4143@Katlego
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8085

paystack.secret.key=${PAYSTACK_SECRET}

paystack.webhook.secret=${PAYSTACK_SECRET}

jwt.secret =your-256-bit-secret-your-256-bit-secret

eureka.client.service-url.defaultZone=http://localhost:8761/eureka


