spring.application.name=TICKET-SERVICE


spring.datasource.url=jdbc:postgresql://localhost:5433/tickets_db
spring.datasource.username=postgres
spring.datasource.password=4143@Katlego
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8084

event.service.url=http://localhost:8083

spring.cache.type=none
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.jpa.properties.hibernate.cache.use_query_cache=false
logging.level.org.hibernate.SQL=DEBUG

jwt.secret =your-256-bit-secret-your-256-bit-secret

eureka.client.service-url.defaultZone=http://localhost:8761/eureka